# Generated by Django 4.2.2 on 2023-07-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fechaFundacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='fotoEstadio',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesClubes'),
        ),
        migrations.AddField(
            model_name='club',
            name='historia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='localidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='provincia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='capacidadEstadio',
            field=models.IntegerField(null=True),
        ),
    ]
