# Generated by Django 4.2.2 on 2023-07-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTickets', '0004_club_autornombre_club_autorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='autorid',
        ),
    ]
